---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - master
  event:
  - push

steps:
- name: git-commit-hash
  image: alpine/git:1.0.7
  commands:
  - echo -n "$(git tag -l --points-at HEAD)" >> .tags
  - echo -n "$(git rev-parse --short HEAD)" >> .tags
  - echo -n "," >> .tags
  - echo -n "latest" >> .tags

- name: docker
  image: plugins/docker
  settings:
    repo: docker.io/kanatakita/portal
    dockerfile: ./Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  depends_on:
  - git-commit-hash

- name: update-manifest
  image: alpine/git:1.0.7
  environment:
    TZ: Asia/Tokyo
    SSH_KEY:
      from_secret: deploy_key
    MANIFEST_REPOSITORY_URL: git@github.com:ShotaKitazawa/manifests-gitops.git
    MANIFEST_PATH: myapp/portal/manifest.yaml
  commands:
  - export REMOTE_URL="$(git config remote.origin.url | sed -e 's|.git$||g')"
  - export REPOSITORY="$(echo $REMOTE_URL | awk -F'/' '{print $NF}')"
  - export COMMIT_HASH="$(git rev-parse --short HEAD)"
  - mkdir /root/.ssh && echo "$SSH_KEY" > /root/.ssh/id_rsa && chmod 0600 /root/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > /root/.ssh/config
  - git clone $MANIFEST_REPOSITORY_URL /root/manifests
  - cd /root/manifests
  - sed -i -e 's|\(deployDate:\).*$|\1 '$(date +%Y-%m-%d)'|g' /root/manifests/$MANIFEST_PATH
  - sed -i -e 's|\(commitHash:\).*$|\1 '$COMMIT_HASH'|g' /root/manifests/$MANIFEST_PATH
  - sed -i -e 's|\(image:.*:\).*$|\1'$COMMIT_HASH'|g' /root/manifests/$MANIFEST_PATH
  - git add .
  - git config user.name DroneCI
  - git config user.email dummy@example.com
  - git commit -m "update by Drone CI ($REMOTE_URL/commit/$COMMIT_HASH)"
  - git push origin HEAD
  depends_on:
  - docker

