name: build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get BRANCH_NAME
        id: branchname
        run: |
          if [ ! -e ${{ github.head_ref }} ]; then
            BRANCH=${{ github.head_ref }}
          else
            BRANCH=$(echo "${{ github.ref }}" | sed -e 's|.*/\(.*\)|\1|')
          fi
          echo "::set-output name=BRANCH::${BRANCH}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kanatakita/portfolio:latest,kanatakita/portfolio:${{ steps.branchname.outputs.BRANCH }}-${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
